services:
  datax-frontend:
    image: amigolli/datax-frontend-prod:latest
    container_name: datax-frontend-prod
    ports:
      - "8050:8050"
    networks:
      - shared-net
#    environment:
#      - NODE_ENV=production

networks:
  shared-net:
    name: datax_prod-net
    external: true