services:
  datax-frontend-dev:
    image: amigolli/datax-frontend-dev:latest
    container_name: datax-frontend-dev
    restart: always
    ports:
      - "8050:8050"
    networks:
      - shared-net
    environment:
      NODE_ENV: development
      PORT: 8050

networks:
  shared-net:
    name: multi-team-dev-deployment_shared-net
    external: true
